export enum InstrumentEnum {
  BassElectric = 'bass-electric',
  Bassoon = 'bassoon',
  Clarinet = 'clarinet',
  Contrabass = 'contrabass',
  Flute = 'flute',
  FrenchHorn = 'french-horn',
  GuitarAcoustic = 'guitar-acoustic',
  GuitarElectric = 'guitar-electric',
  GuitarNylon = 'guitar-nylon',
  Harmonium = 'harmonium',
  Harp = 'harp',
  Organ = 'organ',
  Piano = 'piano',
  Saxophone = 'saxophone',
  Trombone = 'trombone',
  Trumpet = 'trumpet',
  Tuba = 'tuba',
  Violin = 'violin',
  Xylophone = 'xylophone',
}

export const instrumentLabels: Map<InstrumentEnum, string> = new Map([
  [InstrumentEnum.BassElectric, 'Bass Electric'],
  [InstrumentEnum.Bassoon, 'Bassoon'],
  [InstrumentEnum.Clarinet, 'Clarinet'],
  [InstrumentEnum.Contrabass, 'Contrabass'],
  [InstrumentEnum.Flute, 'Flute'],
  [InstrumentEnum.FrenchHorn, 'French Horn'],
  [InstrumentEnum.GuitarAcoustic, 'Guitar Acoustic'],
  [InstrumentEnum.GuitarElectric, 'Guitar Electric'],
  [InstrumentEnum.GuitarNylon, 'Guitar Nylon'],
  [InstrumentEnum.Harmonium, 'Harmonium'],
  [InstrumentEnum.Harp, 'Harp'],
  [InstrumentEnum.Organ, 'Organ'],
  [InstrumentEnum.Piano, 'Piano'],
  [InstrumentEnum.Saxophone, 'Saxophone'],
  [InstrumentEnum.Trombone, 'Trombone'],
  [InstrumentEnum.Trumpet, 'Trumpet'],
  [InstrumentEnum.Tuba, 'Tuba'],
  [InstrumentEnum.Violin, 'Violin'],
  [InstrumentEnum.Xylophone, 'Xylophone'],
])